# Hard rule, applications should not create topics. Just like applications should not create a database or tables in a database. 
auto.create.topics.enable=false # Apps should not create topics
delete.topic.enable=true # Users should be able to delete old topics

# Defaults
max.partitions.per.topic=100 # A misconfigured partition count can destroy a cluster. This is a hard limit to protect the cluster from misconfiguration.
num.partitions=6 # Load should be evenly distributed across partitions. Partitions shoule be devisible by the number of consumers in a consumer group. 6 is a good default for most use cases.
log.retention.hours=168
message.max.bytes=1048576
log.retention.bytes=-1
log.segment.bytes=1073741824

# Dev config
default.replication.factor=1
min.insync.replicas=1

# Prod config
# default.replication.factor=3
# min.insync.replicas=2