import { readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import path from "node:path"


const schemaDirectory = path.resolve('src/integrations/database/schemas')
const schemaFile = 'schema.ts'
const relationsFile = 'relations.ts'
const partitionedFile = 'partitioned.ts'
const partitionTableSuffix = '_default'
const partitionConstSuffix = 'Default'
const filesToKeep = new Set([
    'schema.ts', 'relations.ts', 'partitioned.ts'
])

type PartitionedTable = {
    constName: string        // transactionsDefault
    renamedConstName: string // transactions
    block: string            // full pgTable declaration as pulled
}

// Determine is we are in the correct directory and if it exists
if (!readdirSync(schemaDirectory)) {
    console.log('Schema directory does not exist')
    process.exit(0)
}

// Loop over schemaDirectory and remove files that are not needed by application
for (const entry of readdirSync(schemaDirectory)) {
    if (filesToKeep.has(entry))
        continue;

    rmSync(path.join(schemaDirectory, entry), {
        recursive: true,
        force: true
    })
}

// drizzle-kit pull only introspects the _default partitions, not the partitioned
// parent tables the application actually reads/writes, so move the parents out
const schemaPath = path.join(schemaDirectory, schemaFile)
const schemaSource = readFileSync(schemaPath, 'utf8')
const partitionedTables = extractPartitionedTables(schemaSource)

if (partitionedTables.length === 0) {
    console.log(`No ${partitionTableSuffix} tables found in ${schemaFile}, leaving ${partitionedFile} untouched`)
    process.exit(0)
}

const renamedBlocks: string[] = []
for (const table of partitionedTables) {
    renamedBlocks.push(stripPartitionSuffix(table.block))
}

const tableCode = renamedBlocks.join('\n\n')
const fileLines = [
    '// Generated by scripts/cleanup-drizzle-pull.ts - do not edit by hand.',
    `// Partitioned parent tables derived from the *${partitionTableSuffix} partitions drizzle-kit pulls`,
    ...buildImportLines(schemaSource, tableCode),
    '',
    '',
    tableCode,
    ''
]

writeFileSync(path.join(schemaDirectory, partitionedFile), fileLines.join('\n'))
console.log(`Wrote ${partitionedTables.length} partitioned parent table(s) to ${partitionedFile}`)

writeFileSync(schemaPath, removePartitionedTables(schemaSource, partitionedTables))
console.log(`Removed the ${partitionTableSuffix} tables from ${schemaFile}`)

rewriteRelationsFile(path.join(schemaDirectory, relationsFile), partitionedTables)
console.log(`Pointed ${relationsFile} at the renamed tables in ${partitionedFile}`)


// Collect every table declaration whose table name ends with the partition
// suffix, from its `export const` line down to the closing `});` / `]);`
function extractPartitionedTables(source: string): PartitionedTable[] {
    const tables: PartitionedTable[] = []
    let currentTable: PartitionedTable | null = null
    let currentLines: string[] = []

    for (const line of source.split('\n')) {
        if (currentTable === null) {
            const tableStart = line.match(/^export const (\w+) = pgTable\("(\w+)", \{/)
            const constName = tableStart?.[1]
            const tableName = tableStart?.[2]
            if (constName !== undefined && tableName !== undefined && tableName.endsWith(partitionTableSuffix)) {
                currentTable = {
                    constName,
                    renamedConstName: constName.replace(new RegExp(`${partitionConstSuffix}$`), ''),
                    block: ''
                }
                currentLines = [line]
            }
            continue
        }

        currentLines.push(line)
        if (line === '});' || line === ']);') {
            currentTable.block = currentLines.join('\n')
            tables.push(currentTable)
            currentTable = null
        }
    }

    return tables
}

// transactionsDefault / "transactions_default" become transactions / "transactions".
// Index and constraint names embed the table name, so drop the suffix everywhere
function stripPartitionSuffix(block: string): string {
    const constRename = new RegExp(`^export const (\\w+)${partitionConstSuffix} = pgTable`)
    return block
        .replace(constRename, 'export const $1 = pgTable')
        .replaceAll(partitionTableSuffix, '')
}

// Only import what the copied tables actually use: pg-core helpers, sql,
// and the enums/tables from schema.ts they reference
function buildImportLines(source: string, code: string): string[] {
    const lines: string[] = []

    const pgCoreNames = usedNames(parseNamedImports(source, 'drizzle-orm/pg-core'), code)
    lines.push(`import { ${pgCoreNames.join(', ')} } from "drizzle-orm/pg-core"`)

    if (/\bsql\b/.test(code)) {
        lines.push('import { sql } from "drizzle-orm"')
    }

    const schemaNames = usedNames(parseSchemaExports(source), code)
    if (schemaNames.length > 0) {
        lines.push(`import { ${schemaNames.join(', ')} } from "./${schemaFile}"`)
    }

    return lines
}

// Drop the moved table blocks from schema.ts, then prune import names
// (e.g. char, jsonb) that only those tables used
function removePartitionedTables(source: string, tables: PartitionedTable[]): string {
    let remaining = source
    for (const table of tables) {
        if (remaining.includes(`${table.block}\n\n`)) {
            remaining = remaining.replace(`${table.block}\n\n`, '')
        } else {
            remaining = remaining.replace(table.block, '')
        }
    }
    remaining = remaining.replace(/\n+$/, '\n')

    const bodyLines: string[] = []
    for (const line of remaining.split('\n')) {
        if (!line.startsWith('import ')) {
            bodyLines.push(line)
        }
    }
    const body = bodyLines.join('\n')

    const rebuiltLines: string[] = []
    for (const line of remaining.split('\n')) {
        if (!line.startsWith('import ')) {
            rebuiltLines.push(line)
            continue
        }
        const keptNames = usedNames(parseNamedImports(line, ''), body)
        if (keptNames.length > 0) {
            rebuiltLines.push(line.replace(/\{[^}]*\}/, `{ ${keptNames.join(', ')} }`))
        }
    }
    return rebuiltLines.join('\n')
}

// relations.ts references the _default tables by const name, so rename them and
// import the renamed tables from partitioned.ts instead of schema.ts
function rewriteRelationsFile(filePath: string, tables: PartitionedTable[]) {
    let source = readFileSync(filePath, 'utf8')

    // drizzle-kit emits relative imports without file extensions, which NodeNext rejects
    source = source.replaceAll('from "./schema"', `from "./${schemaFile}"`)

    // Longest names first so a const name embedded in a longer one is never split.
    // The plural form goes before the bare name: the generated relation keys are
    // the const name plus "s" (transactionsDefaults), and the parent names are
    // already plural, so both collapse to the renamed const
    const byLengthDescending = tables.slice().sort(compareConstNameLengthDescending)
    for (const table of byLengthDescending) {
        source = source.replaceAll(`${table.constName}s`, table.renamedConstName)
        source = source.replaceAll(table.constName, table.renamedConstName)
    }

    writeFileSync(filePath, splitSchemaImport(source, tables))
}

// Split the schema.ts import in relations.ts: names that now live in
// partitioned.ts move to their own import line. Matched as one regex over the
// whole file because a formatter may have spread the import over multiple lines
function splitSchemaImport(source: string, tables: PartitionedTable[]): string {
    const renamedNames = new Set<string>()
    for (const table of tables) {
        renamedNames.add(table.renamedConstName)
    }

    const escapedSchemaFile = schemaFile.replaceAll('.', '\\.')
    const schemaImport = source.match(new RegExp(`import \\{([^}]*)\\} from "\\./${escapedSchemaFile}";?`))
    if (schemaImport === null || schemaImport[1] === undefined) {
        console.log(`Warning: no ./${schemaFile} import found in ${relationsFile}, leaving its imports as-is`)
        return source
    }

    const schemaNames: string[] = []
    const partitionedNames: string[] = []
    for (const rawName of schemaImport[1].split(',')) {
        const name = rawName.trim()
        if (name === '')
            continue;

        if (renamedNames.has(name)) {
            partitionedNames.push(name)
        } else {
            schemaNames.push(name)
        }
    }

    const newImports: string[] = []
    if (schemaNames.length > 0) {
        newImports.push(`import { ${schemaNames.join(', ')} } from "./${schemaFile}";`)
    }
    if (partitionedNames.length > 0) {
        newImports.push(`import { ${partitionedNames.join(', ')} } from "./${partitionedFile}";`)
    }
    return source.replace(schemaImport[0], newImports.join('\n'))
}

function compareConstNameLengthDescending(a: PartitionedTable, b: PartitionedTable): number {
    return b.constName.length - a.constName.length
}

// Names inside the braces of an import line; moduleName '' matches any module
function parseNamedImports(source: string, moduleName: string): string[] {
    for (const line of source.split('\n')) {
        if (!line.startsWith('import ') || !line.includes(`"${moduleName}`))
            continue;

        const names: string[] = []
        for (const name of line.slice(line.indexOf('{') + 1, line.indexOf('}')).split(',')) {
            names.push(name.trim())
        }
        return names
    }
    return []
}

function parseSchemaExports(source: string): string[] {
    const names: string[] = []
    for (const line of source.split('\n')) {
        const exportName = line.match(/^export const (\w+) = /)?.[1]
        if (exportName !== undefined) {
            names.push(exportName)
        }
    }
    return names
}

function usedNames(candidates: string[], code: string): string[] {
    const used: string[] = []
    for (const name of candidates) {
        if (new RegExp(`\\b${name}\\b`).test(code)) {
            used.push(name)
        }
    }
    return used
}
