[project]
name = "producers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "avro-datagen[ui]>=0.3.2",
    "confluent-kafka>=2.15.0",
    "dotenv>=0.9.9",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
]

[project.scripts]
start = "app:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
only-include = ["src"]
sources = ["src"]

[dependency-groups]
dev = [
    "poethepoet>=0.48.0",
    "pyright>=1.1.411",
    "ruff>=0.16.0",
]

[tool.poe.tasks]
format = "ruff format src"
lint = "ruff check --fix src"
typecheck = "pyright src"
check = ["format", "lint", "typecheck"]
