// Generated by scripts/cleanup-drizzle-pull.ts - do not edit by hand.
// Partitioned parent tables derived from the *_default partitions drizzle-kit pulls

import { sql } from "drizzle-orm";
import {
	bigint,
	char,
	check,
	foreignKey,
	index,
	integer,
	jsonb,
	pgTable,
	smallint,
	text,
	timestamp,
	uuid
} from "drizzle-orm/pg-core";
import {
	categories,
	categorizationRules,
	directionType,
	ruleSets,
	transactionType
} from "./schema.ts";

export const transactions = pgTable(
	"transactions",
	{
		transactionId: uuid("transaction_id").default(sql`uuidv7()`).notNull(),
		userId: uuid("user_id").notNull(),
		accountId: uuid("account_id").notNull(),
		transactionType: transactionType("transaction_type").notNull(),
		externalId: text("external_id").notNull(),
		occurredAt: timestamp("occurred_at", {
			withTimezone: true,
			mode: "string"
		}).notNull(),
		direction: directionType().notNull(),
		// You can use { mode: "bigint" } if numbers are exceeding js number limitations
		amountMinor: bigint("amount_minor", { mode: "number" }).notNull(),
		currency: char({ length: 3 }).notNull(),
		longDescription: text("long_description"),
		shortDescription: text("short_description"),
		categoryId: smallint("category_id").notNull(),
		ruleVersion: integer("rule_version").notNull(),
		rulePriority: integer("rule_priority"),
		ingestedAt: timestamp("ingested_at", { withTimezone: true, mode: "string" })
			.defaultNow()
			.notNull(),
		metadata: jsonb()
	},
	(table) => [
		index("transactions_user_id_occurred_at_transaction_id_tra_idx").using(
			"btree",
			table.userId.asc().nullsLast().op("timestamptz_ops"),
			table.occurredAt.desc().nullsFirst().op("timestamptz_ops"),
			table.transactionId.desc().nullsFirst().op("timestamptz_ops"),
			table.transactionType.asc().nullsLast().op("uuid_ops"),
			table.direction.asc().nullsLast().op("timestamptz_ops"),
			table.amountMinor.asc().nullsLast().op("timestamptz_ops"),
			table.currency.asc().nullsLast().op("timestamptz_ops"),
			table.categoryId.asc().nullsLast().op("timestamptz_ops"),
			table.shortDescription.asc().nullsLast().op("timestamptz_ops")
		),
		foreignKey({
			columns: [table.categoryId],
			foreignColumns: [categories.categoryId],
			name: "transactions_category_id_fkey"
		}),
		foreignKey({
			columns: [table.ruleVersion],
			foreignColumns: [ruleSets.version],
			name: "transactions_rule_version_fkey"
		}),
		foreignKey({
			columns: [table.ruleVersion, table.rulePriority],
			foreignColumns: [
				categorizationRules.rulesetVersion,
				categorizationRules.priority
			],
			name: "transactions_rule_version_rule_priority_fkey"
		}),
		check("transactions_amount_minor_check", sql`amount_minor > 0`)
	]
);

export const userTransactionOverrides = pgTable(
	"user_transaction_overrides",
	{
		userId: uuid("user_id").notNull(),
		transactionId: uuid("transaction_id").notNull(),
		occurredAt: timestamp("occurred_at", {
			withTimezone: true,
			mode: "string"
		}).notNull(),
		categoryId: smallint("category_id").notNull(),
		createdAt: timestamp("created_at", { withTimezone: true, mode: "string" })
			.defaultNow()
			.notNull(),
		updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string" })
			.defaultNow()
			.notNull(),
		archivedAt: timestamp("archived_at", { withTimezone: true, mode: "string" })
	},
	(table) => [
		foreignKey({
			columns: [table.categoryId],
			foreignColumns: [categories.categoryId],
			name: "user_transaction_overrides_category_id_fkey"
		})
	]
);
